### ISSUE TITLE
Commercial Interest and Consulting

### ISSUE THREAD

**Issue by solvingj** [hsluoyz/rmtsvc#1]
Our group would like to talk with you about using this project for commercial purposes. Please email if you are able to discuss.

**Comment by hsluoyz** [comment]
OK:) I have sent a mail.

**Comment by solvingj** [comment]
Sorry, my phone sent too soon. I emailed you at gmail yesterday, did you receive it?

**Comment by hsluoyz** [comment]
Thanks Jerry! for being interested in my projects:) I saw the mail. But sorry that I already found a full-time job now:) I have updated the status at my GitHub profile:) But I'm still interested in pushing forward these open-source projects by cooperating with companies or organizations. So do you think it still works?

**Comment by Zero3K20** [comment]
https://github.com/hsluoyz/rmtsvc/issues/4
